spring:
  application:
    name: ApplicationTest

  datasource:
    url: jdbc:postgresql://localhost:5432/databaseApp
    username: postgres
    password: admin

  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/SCPI_InvestPLUS
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          audiences: account

jwt:
  auth:
    converter:
      ressource-id: SCPI-client
      principal-attribute: preferred_username

keycloak:
  auth-server-url: http://127.0.0.1:8080
  realm: SCPI_InvestPLUS
  resource: SCPI-client
  public-client: true
  credentials:
    secret: ""
  admin:
    username: admin
    password: admin

logging:
  level:
    org.springframework.security: TRACE

server:
  port: 8085
